apiVersion: v1
kind: ServiceAccount
metadata:
  name: ecr-sa
  namespace: ecr-ns

---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: ecr-role
  namespace: ecr-ns
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list", "watch", "update", "patch"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ecr-rolebinding
  namespace: ecr-ns
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: ecr-role
subjects:
- kind: ServiceAccount
  name: ecr-sa
  namespace: ecr-ns
